version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - '80:80'
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_DATABASE: postgres
      DATABASE_HOST: aws-0-us-east-1.pooler.supabase.com
      DATABASE_PORT: 6543
      DATABASE_USER: postgres.snqtbddrownwjjiejbjb
      DATABASE_PASSWORD: ABCxyz123@abc
      REDIS_HOST: localhost
      REDIS_PORT: 6379
  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
